# Generated by Django 5.1.6 on 2025-02-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_last', models.CharField(blank=True, max_length=4, null=True)),
                ('phone_4', models.CharField(blank=True, max_length=4, null=True)),
                ('phone_6', models.CharField(blank=True, max_length=6, null=True)),
                ('port_asl', models.CharField(blank=True, max_length=6, null=True)),
                ('stan', models.CharField(blank=True, max_length=6, null=True)),
                ('lin', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.department')),
            ],
        ),
    ]
