# Generated by Django 5.1.6 on 2025-02-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.phonerecord')),
            ],
        ),
    ]
