# Generated by Django 5.1.6 on 2025-02-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_failuretype_damagerecord_failure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonerecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.department'),
        ),
    ]
